name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
    - run: npm install
    - run: npm run build
    - name: Confirm Build and Check for Errors
      run: |
        npm run preview &
        sleep 5
        npx cypress run --spec 'cypress/integration/**/*.spec.js'
    - name: Deploy
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
